export const CREATE_POST_REQUEST = "CREATE_POST_REQUEST";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_FAILURE = "CREATE_POST_FAILURE";
export const SET_IMAGE = "SET_IMAGE";
export const REMOVE_IMAGE = "REMOVE_IMAGE";

export const DELETE_POST_REQUEST = "DELETE_POST_REQUEST";
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";
export const DELETE_POST_FAILURE = "DELETE_POST_FAILURE";

export const LIKE_POST_REQUEST = "LIKE_POST_REQUEST";
export const LIKE_POST_SUCCESS = "LIKE_POST_SUCCESS";
export const LIKE_POST_FAILURE = "LIKE_POST_FAILURE";
export const CLEAR = "CLEAR";

export const MY_LIKED_POSTS_REQUEST = "MY_LIKED_POSTS_REQUEST";
export const MY_LIKED_POSTS_SUCCESS = "MY_LIKED_POSTS_SUCCESS";
export const MY_LIKED_POSTS_FAILURE = "MY_LIKED_POSTS_FAILURE";

export const MY_POSTS_REQUEST = "MY_POSTS_REQUEST";
export const MY_POSTS_SUCCESS = "MY_POSTS_SUCCESS";
export const MY_POSTS_FAILURE = "MY_POSTS_FAILURE";

export const ALL_POSTS_REQUEST = "ALL_POSTS_REQUEST";
export const ALL_POSTS_SUCCESS = "ALL_POSTS_SUCCESS";
export const ALL_POSTS_FAILURE = "ALL_POSTS_FAILURE";

export const CREATE_COMMENT_REQUEST = "CREATE_COMMENT_REQUEST";
export const CREATE_COMMENT_SUCCESS = "CREATE_COMMENT_SUCCESS";
export const CREATE_COMMENT_FAILURE = "CREATE_COMMENT_FAILURE";
